### ISSUE TITLE
Low level issue if no server nor auth is passed

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-wizard#67]
```
$ kinto-wizard load /tmp/test.yaml 
Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/kinto-wizard/.venv/bin/kinto-wizard", line 11, in <module>
    load_entry_point('kinto-wizard', 'console_scripts', 'kinto-wizard')()
  File "/home/mathieu/Code/Mozilla/kinto-wizard/kinto_wizard/__main__.py", line 60, in main
    client = cli_utils.create_client_from_args(args)
  File "/home/mathieu/Code/Mozilla/kinto-wizard/.venv/local/lib/python3.6/site-packages/kinto_http/cli_utils.py", line 28, in create_client_from_args
    ignore_batch_4xx=args.ignore_batch_4xx)
  File "/home/mathieu/Code/Mozilla/kinto-wizard/.venv/local/lib/python3.6/site-packages/kinto_http/__init__.py", line 75, in __init__
    self.session = create_session(**session_kwargs)
  File "/home/mathieu/Code/Mozilla/kinto-wizard/.venv/local/lib/python3.6/site-packages/kinto_http/session.py", line 40, in create_session
    raise AttributeError(msg)
AttributeError: You need to either set session or auth + server_url

```

**Comment by Natim** [comment]
That's not a bug, that's a feature... What is the issue?

**Comment by leplatrem** [comment]
Maybe the fact that it was an `AttributeError` got me confused...
